import React from "react";
import "./index.css";

function EnglishTerms() {
  return (
    <>
      <div className="form">
        <div className="rules-form">
          <div className="rules">
            <h2>Terms and Conditions :-</h2>
          </div>{" "}
          <br />
          <p>PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE/WAP/APP. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE/WAP/APP IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS. </p>
          <p>1. This site is only for Maratha People.</p>
          <p>2. We expect that you would complete the online registration process with fairness and honesty in furnishing true, accurate, current, complete information and with providing recent photos of you which will help you to meet your parameters. In order to serve you better if We require additional details you agree to provide it.</p>
          <p>3. Jodidaar also reserves the right to block the registration of your profile on Website/App, if any, in the case of your contact details/links being entered in irrelevant fields or if there are errors in any data entered by the members in their profile. Registration of duplicate profiles of the same person is not allowed in  Website. We Jodidaar shall have full right to suspend or terminate (without any notice) such duplicate profile. </p>
          <p>3. You should verify the information about the places you have taken through your relatives and friends. We will not be responsible for any future issues.</p>
          <p>4. We cannot guarantee that the marriage will take place after registration or that the marriage will take place on a particular day</p>
          <p>5. If you have applied for Divorce, you may register on our website/App by stating "Awaiting Divorce".</p>
          <p>6. Parents should look at the bio data of the boy/girl and select the places according to their educational qualification, financial strength, physical suitability <br /> and expectations.</p>
          <p>7. No one misuses the information taken from us. If found to be so, the membership of the concerned member will be canceled immediately</p>
          <p>8. You are responsible for safeguarding the confidentiality of your Jodidaar login credentials such as your user id, password, OTP, etc., and for restricting access to your computer/mobile to prevent unauthorized access to your account. We, as a Company do not ask for Password and you are cautioned not to share your password to any persons.. You agree to accept responsibility for all activities that occur under your account.</p>
          <p>8. Payment made by Net Banking / Debit / Credit Card/ Paypal/ RTGS/ NEFT/ would be in accordance with the prevailing RBI guidelines. The payments made by any member by way of membership are treated as non-refundable.</p> <br />
          <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
          <br />
          <h5> Customer Care / Customer Service</h5> <br />
          <p>In the event you come across any concerns in our service, then please be free to contact us:</p>
          <p>
            Email ID: jodidaarhelp@gmail.com <br />
            Contact No: +91 11111 22222 <br />
            Address: Washim 

          </p>
        </div>
      </div>
    </>
  );
}

export default EnglishTerms;
